apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: your-registry/uav-vit-mlflow:latest
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_PORT
              valueFrom:
                configMapKeyRef:
                  name: uav-mlops-config
                  key: MLFLOW_PORT
            - name: MLFLOW_ARTIFACT_ROOT
              value: s3://mlflow
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: uav-mlops-config
                  key: MLFLOW_S3_ENDPOINT_URL
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: uav-mlops-config
                  key: AWS_DEFAULT_REGION
            - name: MLFLOW_BACKEND_STORE_URI
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: uav-mlops-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uav-mlops-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: uav-mlops-secrets
                  key: POSTGRES_DB
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: uav-mlops-secrets
                  key: MINIO_ROOT_USER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: uav-mlops-secrets
                  key: MINIO_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
