inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
grpc_inference_port=7070
grpc_management_port=7071
number_of_netty_threads=32
job_queue_size=200
default_response_timeout=120
default_workers_per_model=1
model_store=/home/model-server/model-store
install_py_dep_per_model=false
